# Generated by Django 5.1.1 on 2024-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='vectors',
            field=models.BinaryField(default=None),
        ),
    ]
