# Generated by Django 5.1.1 on 2024-09-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userinfo_image_userinfo_vectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='vectors',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
