# Generated by Django 5.1.1 on 2024-09-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userinfo_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='image_field',
        ),
    ]
