# Generated by Django 5.1.1 on 2024-09-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userinfo_image_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='vectors',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='vector',
            field=models.TextField(null=True),
        ),
    ]
