# Generated by Django 5.1.1 on 2024-10-06 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='drivers_license',
            field=models.ImageField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='government_id',
            field=models.ImageField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='index',
            field=models.ImageField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='medical_insurance',
            field=models.ImageField(blank=True, null=True, upload_to='media/documents/'),
        ),
        migrations.CreateModel(
            name='IDCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='id_checks/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
